In [2]:
#Step 1: Import Libraries
import pandas as pd 
import numpy as np

In [ ]:
# Task 3: Data Cleaning – Dirty Cafe Sales Dataset

#Objective:
#Clean a messy dataset and prepare it for analysis using Python, Pandas, and NumPy.

In [4]:
#Step 2: Load Dataset
df = pd.read_csv(r"C:\Users\ssima\Downloads\dirty_cafe_sales.csv")

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
print("Dataset Shape:", df.shape)
print("\nData Types")
print(df.dtypes)

Dataset Shape: (10000, 8)

Data Types
Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [ ]:
#Standardized text formatting by converting item names to title case and converted transaction dates to datetime format.

In [6]:
#change data type object to numeric
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors="coerce")
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

In [7]:
print("\nData Types")
print(df.dtypes)

Data Types
Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [8]:
print("\nMissing Values")
print(df.isnull().sum())

Missing Values
Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [ ]:
### Missing Value Handling

#- Item: Filled using mode because it is a categorical variable.
#- Quantity: Filled using median because numeric data may contain outliers.
#- Payment Method: Filled using mode.
#- Transaction Date: Filled using forward fill to preserve chronological order.

In [9]:
df["Item"] = df["Item"].fillna(df["Item"].mode()[0])
df["Payment Method"] = df["Payment Method"].fillna(df["Payment Method"].mode()[0])
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())
df["Price Per Unit"] = df["Price Per Unit"].fillna(df["Price Per Unit"].median())
df["Total Spent"] = df["Total Spent"].fillna(
    df["Quantity"] * df["Price Per Unit"]
)
df["Total Spent"] = df["Total Spent"].fillna(df["Total Spent"].median())
df["Transaction Date"] = df["Transaction Date"].ffill()

In [10]:
print("\nMissing Values")
print(df.isnull().sum())

Missing Values
Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [11]:
print("\nDuplicate Rows")
print(df.duplicated().sum())

Duplicate Rows
0

In [12]:
print("\nSummary Statistics")
print(df.describe(include='all'))

Summary Statistics
       Transaction ID   Item      Quantity  Price Per Unit   Total Spent  \
count           10000  10000  10000.000000     10000.00000  10000.000000
unique          10000     10           NaN             NaN           NaN
top       TXN_1961373  Juice           NaN             NaN           NaN
freq                1   1504           NaN             NaN           NaN
mean              NaN    NaN      3.027100         2.95265      8.930750
min               NaN    NaN      1.000000         1.00000      1.000000
25%               NaN    NaN      2.000000         2.00000      4.000000
50%               NaN    NaN      3.000000         3.00000      8.000000
75%               NaN    NaN      4.000000         4.00000     12.000000
max               NaN    NaN      5.000000         5.00000     25.000000
std               NaN    NaN      1.384614         1.24396      5.997122

        Payment Method  Location               Transaction Date
count            10000     10000                          10000
unique               5         4                            NaN
top     Digital Wallet  Takeaway                            NaN
freq              4870      6287                            NaN
mean               NaN       NaN  2023-07-02 00:30:31.680000256
min                NaN       NaN            2023-01-01 00:00:00
25%                NaN       NaN            2023-04-01 00:00:00
50%                NaN       NaN            2023-07-02 00:00:00
75%                NaN       NaN            2023-10-02 00:00:00
max                NaN       NaN            2023-12-31 00:00:00
std                NaN       NaN                            NaN

In [13]:
print(df.head(10))

  Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
0    TXN_1961373    Coffee       2.0             2.0          4.0
1    TXN_4977031      Cake       4.0             3.0         12.0
2    TXN_4271903    Cookie       4.0             1.0          4.0
3    TXN_7034554     Salad       2.0             5.0         10.0
4    TXN_3160411    Coffee       2.0             2.0          4.0
5    TXN_2602893  Smoothie       5.0             4.0         20.0
6    TXN_4433211   UNKNOWN       3.0             3.0          9.0
7    TXN_6699534  Sandwich       4.0             4.0         16.0
8    TXN_4717867     Juice       5.0             3.0         15.0
9    TXN_2064365  Sandwich       5.0             4.0         20.0

   Payment Method  Location Transaction Date
0     Credit Card  Takeaway       2023-09-08
1            Cash  In-store       2023-05-16
2     Credit Card  In-store       2023-07-19
3         UNKNOWN   UNKNOWN       2023-04-27
4  Digital Wallet  In-store       2023-06-11
5     Credit Card  Takeaway       2023-03-31
6           ERROR  Takeaway       2023-10-06
7            Cash   UNKNOWN       2023-10-28
8  Digital Wallet  Takeaway       2023-07-28
9  Digital Wallet  In-store       2023-12-31

In [14]:
print(df["Quantity"].unique()[:20])
print(df["Price Per Unit"].unique()[:20])
print(df["Total Spent"].unique()[:20])

[2. 4. 5. 3. 1.]
[2.  3.  1.  5.  4.  1.5]
[ 4.  12.  10.  20.   9.  16.  15.  25.   8.   5.   3.   6.   2.   1.
  7.5  4.5  1.5]

In [15]:
print(df["Item"].unique()[:20])
print(df["Location"].unique()[:20])
print(df["Payment Method"].unique()[:20])

['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' 'Juice'
 'ERROR' 'Tea']
['Takeaway' 'In-store' 'UNKNOWN' 'ERROR']
['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR']

In [16]:
df["Item"] = df["Item"].replace(
    ["ERROR", "Unknown", "NaN", "error", "UNKNOWN", "nan"],
    np.nan
)
df["Item"] = df["Item"].fillna(df["Item"].mode()[0])
print(df["Item"].unique()[:20])

['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'Juice' 'Sandwich' 'Tea']

In [17]:
df["Location"] = df["Location"].replace(
    ["ERROR", "Unknown", "NaN", "error", "UNKNOWN", "nan"],
    np.nan
)
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])
print(df["Location"].unique()[:20])

['Takeaway' 'In-store']

In [18]:
df["Total Spent"] = df["Total Spent"].replace(
    ["ERROR", "Unknown", "NaN", "error", "UNKNOWN", "nan"],
    np.nan
)
df["Total Spent"] = df["Total Spent"].fillna(df["Total Spent"].mode()[0])
print(df["Total Spent"].isnull().sum())
print(df["Total Spent"].unique())

0
[ 4.  12.  10.  20.   9.  16.  15.  25.   8.   5.   3.   6.   2.   1.
  7.5  4.5  1.5]

In [19]:
df["Payment Method"] = df["Payment Method"].replace(
    ["ERROR", "Unknown", "NaN", "error", "UNKNOWN", "nan"],
    np.nan
)
df["Payment Method"] = df["Payment Method"].fillna(df["Payment Method"].mode()[0])
print(df["Payment Method"].isnull().sum())
print(df["Payment Method"].unique())

0
['Credit Card' 'Cash' 'Digital Wallet']

In [20]:
print(df["Transaction ID"].unique()[:20])
print(df["Item"].unique()[:20])
print(df["Payment Method"].unique()[:20])
print(df["Location"].unique()[:20])
print(df["Transaction Date"].unique()[:20])

['TXN_1961373' 'TXN_4977031' 'TXN_4271903' 'TXN_7034554' 'TXN_3160411'
 'TXN_2602893' 'TXN_4433211' 'TXN_6699534' 'TXN_4717867' 'TXN_2064365'
 'TXN_2548360' 'TXN_3051279' 'TXN_7619095' 'TXN_9437049' 'TXN_8915701'
 'TXN_2847255' 'TXN_3765707' 'TXN_6769710' 'TXN_8876618' 'TXN_3709394']
['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'Juice' 'Sandwich' 'Tea']
['Credit Card' 'Cash' 'Digital Wallet']
['Takeaway' 'In-store']
<DatetimeArray>
['2023-09-08 00:00:00', '2023-05-16 00:00:00', '2023-07-19 00:00:00',
 '2023-04-27 00:00:00', '2023-06-11 00:00:00', '2023-03-31 00:00:00',
 '2023-10-06 00:00:00', '2023-10-28 00:00:00', '2023-07-28 00:00:00',
 '2023-12-31 00:00:00', '2023-11-07 00:00:00', '2023-05-03 00:00:00',
 '2023-06-01 00:00:00', '2023-03-21 00:00:00', '2023-11-15 00:00:00',
 '2023-06-10 00:00:00', '2023-02-24 00:00:00', '2023-03-25 00:00:00',
 '2023-01-15 00:00:00', '2023-04-04 00:00:00']
Length: 20, dtype: datetime64[ns]

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.duplicated().sum()

0

In [23]:
df["Item"] = df["Item"].str.title()

In [24]:
print(df["Item"].unique())

['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'Juice' 'Sandwich' 'Tea']

In [25]:
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [26]:
outliers = df[(df["Quantity"] < lower) | (df["Quantity"] > upper)]

print(outliers)

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [27]:
Q1 = df["Price Per Unit"].quantile(0.25)
Q3 = df["Price Per Unit"].quantile(0.75)
IQR = Q3 - Q1
Q1 = df["Total Spent"].quantile(0.25)
Q3 = df["Total Spent"].quantile(0.75)

In [28]:
outliers = df[(df["Quantity"] < lower) | (df["Quantity"] > upper)]

In [29]:
#Outliers were detected using the IQR method.

#Quantity:
#Retained because bulk purchases may be valid.

#Price Per Unit:
#Capped to reduce the impact of extreme values.

#Total Spent:
#Retained after validation because large orders are possible.

In [30]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

,Quantity,Price Per Unit,Total Spent,Transaction Date
count,10000.000000,10000.00000,10000.000000,10000
mean,3.027100,2.95265,8.930750,2023-07-02 00:30:31.680000256
min,1.000000,1.00000,1.000000,2023-01-01 00:00:00
25%,2.000000,2.00000,4.000000,2023-04-01 00:00:00
50%,3.000000,3.00000,8.000000,2023-07-02 00:00:00
75%,4.000000,4.00000,12.000000,2023-10-02 00:00:00
max,5.000000,5.00000,25.000000,2023-12-31 00:00:00
std,1.384614,1.24396,5.997122,NaN

In [31]:
df.to_csv("cleaned_cafe_sales.csv", index=False)

In [32]:
#The Dirty Cafe Sales dataset was successfully cleaned.

#• Missing values handled.
#• Invalid values replaced.
#• Duplicate rows removed.
#• Data types corrected.
#• Outliers detected using IQR.
#• Cleaned dataset exported successfully.

In [33]:
df.memory_usage(deep=True).sum()

2636354

In [34]:
df[df["Price Per Unit"] <= 0]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [35]:
df.to_csv("cleaned_cafe_sales.csv", index=False)

In [36]:
import os

print(os.getcwd())

C:\Users\ssima

In [37]:
import os

print(os.listdir())

['-1.14-windows.xml', '.android', '.bash_history', '.copilot', '.dropbox_bi', '.git', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.matplotlib', '.sf', '.TianTianVM', '.vscode', '6april.ipynb', 'AppData', 'Application Data', 'bar_chart.ipynb', 'charts', 'classwork.ipynb', 'cleaned_cafe_sales.csv', 'cleaning data.ipynb', 'compressed.csv', 'Contacts', 'Cookies', 'Documents', 'Documents - Copy', 'Downloads', 'downloadtemp', 'Dropbox', 'Favorites', 'fraud_data_generation.ipynb', 'fraud_detection_analysis.ipynb', 'fraud_ecommerce_1M.csv', 'histogram.ipynb', 'IntelGraphicsProfiles', 'lab1 jupyter.ipynb', 'line_chart.ipynb', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{59b90c02-ab0a-11ef-ae7d-8ffbd59348a1}.TM.blf', 'NTUSER.DAT{59b90c02-ab0a-11ef-ae7d-8ffbd59348a1}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{59b90c02-ab0a-11ef-ae7d-8ffbd59348a1}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'pie_chart.ipynb', 'PixelSee', 'PrintHood', 'README.md', 'Recent', 'Saved Games', 'Scatter Plots.ipynb', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled10.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'Untitled9.ipynb', 'Videos']

In [38]:
df.to_csv(r"C:\Users\ssima\Downloads\cleaned_cafe_sales.csv", index=False)